import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const saans = localFont({
  src: "./fonts/SaansUprights-VF.woff2",
  weight: "300 700",
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saans.className} antialiased bg-[#EAE5E3]`}>
        {children}
      </body>
    </html>
  );
}
